### PR TITLE
[WIP]Update dependency on Nimble with testDependencies

### PR DESCRIPTION
**Pull request by takecian**
Discussed in #545 , I replaced dependencies with testDependencies.

### CODE REVIEW

**Comment by takecian** [comment]
I got new error, `error: the module at Sources/QuickTests has an invalid name ('QuickTests'): the name of a non-test module has a ‘Tests’ suffix`.

I think this error occured due to [Proposal: SE-0019](https://github.com/apple/swift-evolution/blob/master/proposals/0019-package-manager-testing.md), we have to change directory name of test code.

**Comment by ikesyo** [comment]
> we have to change directory name of test code

That is already done in #510.

**Comment by ikesyo** [comment]
Unfortunately, `testDependencies` are removed in recent development snapshots 😢 : https://github.com/apple/swift-package-manager/pull/597

**Comment by takecian** [comment]
Ok..I'll close this..

**Pull request closed without merging**
