### PR TITLE
[DON'T MERGE] Test Travis CI to see whether xctool is working

### PR DESCRIPTION
**Pull request by modocache**
According to @mokagio in https://github.com/Quick/Quick/issues/389, xctool should be working properly now. Let's see what CI has to say! :)

### CODE REVIEW

**Comment by mokagio** [comment]
😞 I was 100% sure that was the case, as per https://github.com/Quick/Quick/commit/7c4b41be83cfbff571fc3ba14e384907128b263c#diff-d6c1eb8c6cb0df43a9d133c60e0f564f...

The build at the time *did* work https://circleci.com/gh/mokagio/Quick/20

New versions of Xcode and [xctool](https://github.com/facebook/xctool/releases) have been released in the meantime... New things might be broken (or re-broken) now.

Good thinking @modocache in not trusting my word :D I'll see what I can do about it 👍

**Comment by mokagio** [comment]
[xctool + iOS](https://travis-ci.org/Quick/Quick/jobs/139312797) failed due to a timeout after the tests suite run successfully:

```
  [Info] Collecting info for testables...
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

[xctool + OS X ](https://travis-ci.org/Quick/Quick/jobs/139312795) failed due to a timeout after the tests suite run successfully as well:

```
  [Info] Collecting info for testables...
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

[xctool + tvOS](https://travis-ci.org/Quick/Quick/jobs/139312798) failed due to a compilation error:

```
/Users/travis/build/Quick/Quick/Sources/QuickTests/FunctionalTests/Configuration/BeforeEach/Configuration+BeforeEachTests.swift:3:8: 
  error: module file's minimum deployment target is tvos9.2 v9.2: 
    /Users/travis/Library/Developer/Xcode/DerivedData/Quick-gfagarrcmybciseosvzumpzfbbzd/Build/Products/Debug-appletvsimulator/Nimble.framework/Modules/Nimble.swiftmodule/x86_64.swiftmodule

import Nimble
       ^
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      ✗ Compile Swift source files (249 ms)
```

🤔 I guess the first step would be understanding who's responsible for the failures: xctool, our setup, Travis.

**Comment by modocache** [comment]
> Good thinking @modocache in not trusting my word

Haha, it's not like that!! 😝 

But yes, if you can help diagnose this at all, that'd be great. Our CI constantly shows up red because of xctool; it'd be nice to keep testing it, but it makes it hard to contribute.

**Comment by istx25** [comment]
I think we should try to get CI fixed. From my understanding, it's currently broken?

**Comment by istx25** [comment]
Also, is it save to close this PR now?

**Pull request closed without merging**
