### PR TITLE
[Translation]Translate ArrangeActAssert chapter into Chinese

### PR DESCRIPTION
**Pull request by wongzigii**
This PR is the translation of the **ArrangeActAssert** chapter.

### CODE REVIEW

**Comment by istx25** [comment]
Whoops, meant to add the `needs-review` tag. Let us know when you've finished with this one. :)

**Comment by wongzigii** [comment]
Just fix the chapter name for more meaningful.

**Comment by wongzigii** [comment]
Ready for merge now. :D

**Comment by istx25** [comment]
Awesome, thank you @wongzigii.

**Pull request merged**
