### PR TITLE
iOS7 Support

### LINKED ISSUE #206: Do Quick/Nimble support iOS 7?
I received the following email:

I am trying to use them both on an Obj-C project targeting iOS 7 and up. After I include the frameworks and add them to the build-phases/Link-binary-with-libraries, my build fails with the following error:

```
ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/Nimble.framework/Nimble) for architecture x86_64
clang: error: linker command failed with exit code 1
```

It seems Quick & Nimble are embedded/dynamic frameworks and they do not work on iOS 7.
I also read somewhere that it is impossible to create static frameworks from swift code.

So, Is there some way to use Quick/Nimble for ObjC/iOS7? do you know if someone succeed in that path?

### PR DESCRIPTION
**Pull request by tibr**
This pull request adds the correct Nimble reference to #253 which fixes #206

### CODE REVIEW

**Comment by tibr** [comment]
Not sure why the build is failing, `rake` works for me locally. Any ideas?

**Comment by mkauppila** [comment]
I'd reckon that builds keep failing because Travis doesn't yet support the latest version of Swift :traffic_light: 

I think this PR is ready for a merge. What do you @Quick/contributors think?

**Comment by jeffh** [comment]
Thanks @tibr and @marciok!

@mkauppila, feel free to merge this in after a couple of days if it looks good to you.

**Comment by mkauppila** [comment]
@jeffh Thanks for doing the job :+1:  Yeah, I know, quite frankly forgot this :blush:

**Comment by marciok** [comment]
Thanks everybody 😊😊😊

**Comment by jeffh** [comment]
No worries @mkauppila :smile:

**Pull request merged**
