### PR TITLE
Fix example description in QuickSpec.h

### PR DESCRIPTION
**Pull request by muukii**
QuickSpec.spec() is instance method.

### CODE REVIEW

**Comment by phatblat** [comment]
True, the `spec` method is not a class method. However, that example is Swift in an Objective-C header. Would you mind changing the example to Objective-C?

**Comment by muukii** [comment]
@phatblat 
Sure.
But, original example was written by Swift.
Still do you change it to Objective-C?

**Comment by phatblat** [comment]
Never mind. This example shows up in the docs for both objc and swift.

screen_shot_2016-04-06_at_8_15_49_pm

**Comment by muukii** [comment]
Thank you!

**Pull request merged**
