### PR TITLE
Add Swift 5 support to Quick.podspec

### PR DESCRIPTION
**Pull request by ethansinjin**
Resolves issue #895. Based on Nimble.podspec

Checklist:
 - [x] Does this have tests? (No)
 - [x] Does this have documentation? (No)
 - [x] Does this break the public API (Requires major version bump)? (No)
 - [x] Is this a new feature (Requires minor version bump)?
This may require a minor version bump in order to propagate on CocoaPods correctly

### CODE REVIEW

**Comment by Oleg-Marchik-Neklo** [comment]
@ethansinjin  please, add  '5.1' to the list

**Comment by benasher44** [comment]
osx_image for the `CocoaPods and Danger` job needs to be updated from 10.1 to at least 10.2

**Comment by ethansinjin** [comment]
@Oleg-Marchik-Neklo I didn't include 5.1 because Xcode 11 is still in beta, and Quick/Nimble doesn't include it either. If any of the project maintainers want to add it, feel free to edit this PR or comment below!

**Comment by ikesyo** [comment]
Superseded by #919.

**Pull request closed without merging**
