### PR TITLE
Update Carthage installation instructions

### PR DESCRIPTION
**Pull request by mokagio**
See https://github.com/Quick/Quick/issues/347

If you guys are not happy with the picture (👇) I'm happy to make another one. I had that one already from [this blogpost I wrote](http://www.mokacoding.com/blog/setting-up-testing-libraries-with-carthage-xcode7/) (_shameless plug_ 😁)

### CODE REVIEW

**Comment by ikesyo** [comment]
It seems that Framework Search Paths issue is fixed in Xcode 7 beta 4.

**Comment by mokagio** [comment]
Oh really? Thanks! I'll investigate 👍



—
Gio

**Comment by mokagio** [comment]
@ikesyo I tried on a fresh project with Xcode 7 Beta 4 and I confirm it's fixed. Thanks for the heads up :beers: 

Closing this now :+1:

**Comment by acecilia** [comment]
Hi:
I am on Xcode Version 10.1 (10B61). I am having this problem, If I do not add `$(PROJECT_DIR)/Carthage/Build/iOS` to the `FRAMEWORK_SEARCH_PATHS`, then I get `no such module <module_name>` errors. My root directory is as follows:

```
APP.xcodeproj
APP.xcworkspace
Cartfile
Cartfile.resolved
Carthage
... (other files)
```

Any help would be appreciated, as I am using cocoapods also, and setting the `FRAMEWORK_SEARCH_PATHS` has incompatibility issues (as cocoapods is also setting its values there).

**Pull request closed without merging**
