### PR TITLE
[Documentation] Add Japanese translation

### PR DESCRIPTION
**Pull request by modocache**
This pull requests translates all of the Quick documentation into Japanese. This is mostly thanks to @takecian! :bow: :sparkles: 

I've invited @takecian to join the Quick GitHub org so that he can help keep the English and Japanese documentation up-to-date (and of course work on the source code too, if he pleases). I can also help out with the Japanese documentation.

I'm submitting a pull request because I'd like some feedback from @Quick/contributors:

- It's still my opinion that documentation on testing in general, outside of instructions on how to use Quick itself, is probably [the most valuable thing we can contribute](http://modocache.io/better-tests-for-all) to the Apple platform's testing tools. I *think* I prefer documentation included in the main repository, as opposed to a GitHub wiki page, or a GitHub pages site. This makes it easy to find, easy to read, easy to contribute to, and requires no additional work on our part. Does anyone have any thoughts on this?
- I'd love to see additional translations, especially Chinese. A lot of traffic to the Quick repository comes from China and Taiwan. Does the existence of several translations, with potentially more to come, affect your thoughts on whether to keep all the documentation in the main Quick repository?

### CODE REVIEW

**Comment by orta** [comment]
Proof that it was definitely worth all the write-up.

**Comment by modocache** [comment]
Merged! Of course, opinions from @Quick/contributors are still welcome. :100:

**Comment by briancroom** [comment]
This is *really* cool. Thanks a lot @takecian for your contributions here.

:+1: from me on keeping the docs right in the repo for all the reasons @modocache listed. I remember stumbling onto the Documentation directory here long before I started actually using Quick, and being very impressed at the effort that had been put into them.

**Pull request merged**
