### PR TITLE
Fix Markdown syntax in Japanese documentation

### PR DESCRIPTION
**Pull request by JPMartha**
Fixed Markdown syntax in Japanese documentation, and removed English text.

By the way, if needed, I will translate the description of Swift Package Manager in `InstallingQuick.md` into Japanese.

### CODE REVIEW

**Comment by takecian** [comment]
💯

**Comment by istx25** [comment]
@takecian In the future, if there is a PR with the tag `GH Review: needs-review` and you're merging it. Please change the tag to `GH Review: accepted` if you have reviewed the changes.

**Comment by istx25** [comment]
Thanks for the contribution @JPMartha.

**Comment by takecian** [comment]
@istx25 Sure!

**Pull request merged**
