### PR TITLE
Added a comment about Xcode limitations

### PR DESCRIPTION
**Pull request by alper**
As per this discussion: https://github.com/Quick/Quick/issues/665

### CODE REVIEW

**Comment by istx25** [comment]
Thanks for making this change, @alper.

**Comment by istx25** [comment]
Fair. @alper, mind filing another PR with that change?

**Comment by alper** [comment]
Thanks for the merge. I think if people are annoyed enough by it, they will read the linked issue and take action?

**Comment by jeffh** [comment]
Yep. That's the best way to get proper integration into Xcode.

**Pull request merged**
