### PR TITLE
Updates Nimble submdule commit.

### PR DESCRIPTION
**Pull request by ashfurrow**
[As discussed](https://github.com/Quick/Nimble/pull/271#issuecomment-201082777), we need to update this to get the latest fix for #494.

### CODE REVIEW

**Comment by modocache** [comment]
Thanks!! Hopefully peeps aren't using the version of Nimble Quick's tests depend on as their Nimble dependency, but I have a feeling some do.

Feel free to merge once CI passes.

**Comment by ashfurrow** [comment]
Hmm, both builds stalled out. Should I just try to restart?

**Comment by ashfurrow** [comment]
Ha, looks like this happened the last time we upped the Nimble submodule commit: https://github.com/Quick/Quick/pull/505 I'll try restarting.

**Comment by ashfurrow** [comment]
The [same test](https://github.com/Quick/Quick/blob/3a1d88fb81476001c62f086dbd94bb0f5354f1a3/Sources/QuickTests/FunctionalTests/FailureTests%2BObjC.m#L56-L59) is failing on both CI providers, probably not a coincidence... Since the Nimble change we're trying to bring in has to do with _when_ test observation starts, I'm willing to bet it's a valid failure. I'll look into it and report back.

**Comment by ashfurrow** [comment]
Tests didn't fail when running within Xcode. [Invoking](https://github.com/ashfurrow/Quick/blob/3a1d88fb81476001c62f086dbd94bb0f5354f1a3/Rakefile#L32) `xcodebuild -workspace Quick.xcworkspace -scheme Quick-OSX clean test` led to :green_apple: tests. Looking into possible `xctool` issues.

**Comment by ashfurrow** [comment]
Hmm, might be a trickier issue than expected. Kif ran into [similar problems](https://github.com/kif-framework/KIF/pull/819) that https://github.com/Quick/Nimble/pull/271 was supposed to fix, but decided not to use the solution we did `dispatch_async`. However, their solution appears to [remove any call to `addTestObserver:`](https://github.com/kif-framework/KIF/pull/819/files#diff-d869217c7fbf012a7678c6ab49fcdbc1L46). I don't want to ask for clarification there without a better understanding of what `XCTestObservationCenter` is and why we need it.

Suggestions on how to proceed would be awesome :bow: I feel a little out of my depth.

**Comment by phatblat** [comment]
Looks like KIF's solution was to move their test observation functionality into the `KIFTestCase.setUp` method to start before each test. Nimble doesn't have the an `XCTestCase` subclass to move its logic to.

The Nimble test observation logic appears to only be used when [`_runtime(_ObjC)`](https://github.com/Quick/Nimble/blob/master/Sources/Nimble/Adapters/NimbleXCTestHandler.swift#L40-L51) so that it can [testCase.recordFailureWithDescription](https://github.com/Quick/Nimble/blob/master/Sources/Nimble/Adapters/NimbleXCTestHandler.swift#L68) instead of `XCTFail` on the swift side.

**Comment by ashfurrow** [comment]
Hmm. You reckon its worth opening an issue on Nimble to discuss options? Maybe there's another hook we could use, and `dispatch_once` to add the observer.

**Comment by phatblat** [comment]
Yes, let's open a Nimble issue to discuss. I've been doing some debugging and have a theory.

**Comment by phatblat** [comment]
@ashfurrow can you update your branch to Quick/Nimble@1a9e53e2d74363e1d6320a87a5028bc234c9a4d4?

**Comment by ashfurrow** [comment]
Done :+1: Let's see how CI goes :smile:

**Comment by phatblat** [comment]
Aw yeah! :rocket:

**Comment by briancroom** [comment]
Awesome! Thanks guys 🙌

**Comment by phatblat** [comment]
Time for a release?

**Comment by modocache** [comment]
Sure! @phatblat, I've added you as a `pod trunk` owner, so you should be able to tag a release. Use `script/release` to do so 👍

**Comment by briancroom** [comment]
There's also the nice section in the Contributing document about making releases: https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md#creating-a-release

**Pull request merged**
