### PR TITLE
(Temporarily) Remove async support from Quick

### PR DESCRIPTION
**Pull request by younata**
Async support was released before it was ready.

There have been several issues about the way Quick forces async behavior. [Migrating is a massive pain in the ass. There's no way to get Nimble's `toEventually` to work with Objective-C tests](https://github.com/Quick/Quick/issues/1189). There's no clear way to force a test (or part of a test) to run on the main actor (the method [mentioned in the documentation](https://github.com/Quick/Quick/blob/main/Documentation/en-us/AsyncAwait.md#running-test-code-on-the-main-thread) doesn't work if you use the Swift Package Manager version of Quick). (issues: [1182](https://github.com/Quick/Quick/issues/1182), [1180](https://github.com/Quick/Quick/issues/1180), [1179](https://github.com/Quick/Quick/issues/1179)). It's been a mess.

Quick 7 will introduce a different (better) way of handling async. I'm still in the process of prototyping that out, but it will involve a separate test class (I'm using `AsyncSpec` for now). My current prototype is based on ResultBuilder, but I want to expand on that and see how it scales before committing to that direction. I'll post a draft PR when I have something semi-usable.

- This PR is targeting the `quick_7` branch. I'm going to target all of the async changes to this branch. I'll also keep it up to date with main to make this relatively easy to keep track of.
- The `main` branch will represent Quick 6 until I merge in the `quick_7` branch.

### CODE REVIEW

**Comment by tahirmt** [comment]
Does this mean big changes in v7.0.0 potentially needing to revert many of the things that were changed in v6?

**Comment by younata** [comment]
> Does this mean big changes in v7.0.0 potentially needing to revert many of the things that were changed in v6?

In a sense, yes. In v7, QuickSpec subclasses will revert back to the older, v5 behavior of running all tests synchronously, on the main thread. However, Async specs will 100% still be a thing in v7. They'll need to subclass a different class in order to get the async behavior (e.g. `class MyAsyncSpec: AsyncSpec` instead of `class MyAsyncSpec: QuickSpec`).

I'm still figuring out/testing how to get this all to work out. For example, [using result builders](https://github.com/Quick/Quick/pull/1194) was one attempt that didn't pan out. But it was certainly educational in terms of guiding other paths to try.

**Comment by tahirmt** [comment]
Thank you for the context. The reason I asked is because I’ve spent the better part of the last month migrating our tests to Quick 6. A total of around 17000 tests. Previously we had written async versions of `it`, `beforeEach` etc. so we’d swap to `asyncIt` whenever we needed to break into an async context. This refactor of Quick 6 has been among the biggest in our tests so far. The branches are not merged yet still. 

Are you imagining `AsyncSpec` to behave how `QuickSpec` behaves in Quick 6 where the entire spec would run on the cooperative threads and we would need to use `MainActor` for things that require the main thread?

**Comment by younata** [comment]
> This refactor of Quick 6 has been among the biggest in our tests so far. The branches are not merged yet still.

My apologies for the breakage I caused.

> Are you imagining AsyncSpec to behave how QuickSpec behaves in Quick 6 where the entire spec would run on the cooperative threads and we would need to use MainActor for things that require the main thread?

Yes. Additionally, I'd like to add some kind of convenience to force all of the closures to run on the main thread, but I don't know what that will look like yet.

**Pull request merged**
