### PR TITLE
Review BehavioralTesting.md

### PR DESCRIPTION
**Pull request by wongzigii**
This PR is the review of **BehavioralTesting** translation.

### CODE REVIEW

**Comment by wongzigii** [comment]
I've noticed that @LinShiwei is contributing the Chinese doc, too. Would like to hear your voice  about the translation format. 😃

**Comment by modocache** [comment]
It would be awesome if you and @LinShiwei could work together, reviewing each others' work! I can't read or write Chinese very well, so I don't have much input here. :)

I'll take a look at the commits soon, and if you and @LinShiwei are interested you two could have commit access to make it easier to make updates.

**Comment by LinShiwei** [comment]
It's my pleasure to work with you @wongzigii .

 In terms of translation format,  I have found that you add spaces between Chinese characters and English letters in your translation, which looks nicer.  I have done that in my latest translation. I also use Chinese punctuation carefully though it may  still have some mistakes. 

And thank you for your review of **BehavioralTesting**.

**Comment by wongzigii** [comment]
@LinShiwei  Wonderful! By the way, don't hesitate to point out my PR if anything's missing or something that could be better. I will appreciate that.

**Comment by istx25** [comment]
Awesome. Would you say this PR has been reviewed and is ready to be merged?

**Comment by wongzigii** [comment]
cc @LinShiwei

**Comment by LinShiwei** [comment]
Yes, ready to be merged.

**Comment by istx25** [comment]
Awesome, sounds good. Just so you know - you two can lead the translation front for Quick and Nimble in Chinese if you're interested. You can merge the PRs yourself if one of you looks over the other's work. Just to ensure we haven't missed anything (fresh pair of eyes).

**Comment by istx25** [comment]
Please use the `documentation` tag on documentation related PRs/issues and make use of the `GH Review: ~` tags as well.

**Comment by istx25** [comment]
Just to make my life a little easier and for future organisation. :)

**Comment by wongzigii** [comment]
@istx25 Will do my best!

**Comment by istx25** [comment]
Do you have the privileges to merge and tag PRs on your own? If not, I can have one of the admins add you (my privilege level only goes so far haha).

**Comment by wongzigii** [comment]
Unfortunately, not yet.

**Comment by istx25** [comment]
@modocache: Would you be able to give @wongzigii and @LinShiwei write access?

**Pull request merged**
