### PR TITLE
iOS7 Support, fixes #206

### LINKED ISSUE #206: Do Quick/Nimble support iOS 7?
I received the following email:

I am trying to use them both on an Obj-C project targeting iOS 7 and up. After I include the frameworks and add them to the build-phases/Link-binary-with-libraries, my build fails with the following error:

```
ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/Nimble.framework/Nimble) for architecture x86_64
clang: error: linker command failed with exit code 1
```

It seems Quick & Nimble are embedded/dynamic frameworks and they do not work on iOS 7.
I also read somewhere that it is impossible to create static frameworks from swift code.

So, Is there some way to use Quick/Nimble for ObjC/iOS7? do you know if someone succeed in that path?

### PR DESCRIPTION
**Pull request by marciok**
As @modocache suggested, #206

### CODE REVIEW

**Comment by modocache** [comment]
It looks like the tests are failing, despite the fact that this is being run against the Swift 1.1 branch. Any ideas?

**Comment by orta** [comment]
`ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/Nimble.framework/Nimble) for architecture i386`

**Comment by marciok** [comment]
Hi guys, I think found what the problem was:

I had to set the **Deployment target to 7.0 at the Nimble-iOS target** BUT
I'm not sure how to proceed to fix that because the submodule is pointing to a different commit and my changes are on  [this one]
(https://github.com/marciok/Nimble/commit/bd0f5782b931fcd954d81ea69807b560d8f947ce).

How can I change the subproject commit without breaking the build ? 

Thanks a lot.

**Comment by jeffh** [comment]
Hey @marciok, could you send a pull request with your changes to Nimble. Once that's merged into Nimble then the submodule that Quick points to can be updated.

**Comment by tibr** [comment]
@jeffh I think he already did: https://github.com/Quick/Nimble/pull/102

**Comment by jeffh** [comment]
My bad, I must of missed that. It's merged now.

**Comment by marciok** [comment]
Someone could re-run this build for me please ?
It should pass, [Quick/Nimble#102](https://github.com/Quick/Nimble/pull/102) was merged.

Thanks

**Comment by paulyoung** [comment]
I restarted the build :+1:

**Comment by yuriferretti-luizalabs** [comment]
@marciok Is your Quick fork working with iOS 7 deployment targets?

**Comment by marciok** [comment]
@yuriferretti-luizalabs yes

**Comment by marciok** [comment]
The build didn't pass because it's still fetching the commit: **'31c843aa3104de8d180eca3e9a4e924621b03299'**  :disappointed: 

nor the: **1088d5f70497f34be946e3e2829a10529f7bea8e** with the iOS7 support, why it didn't fetch the latest one ? sorry I'm confused.

**Comment by tibr** [comment]
@marciok I think you still have to update the reference in `Externals/Nimble`. The file in this pull request references `31c843aa3104de8d180eca3e9a4e924621b03299`.

**Pull request merged**
