### PR TITLE
Fix empty 'Selected tests' suites

### LINKED ISSUE #891: Trying to run a specific spec does not run any tests
What did you do?

Running a spec with the play button in Xcode results in no tests being run. I raised this earlier in #889 but it was immediately closed. 

Upon further investigation I've discovered the fix in #873 is causing this issue. Specifically the `defaultTestSuite` is not called when running a specific spec.

What did you expect to happen?

The specific spec to be run

What actually happened instead?

No tests were run

Environment

List the software versions you're using:

Quick: latest from master 32804c3
Nimble: 8.0.1
Xcode Version: 10.2.1 (Open Xcode; In menubar: Xcode > About Xcode)
Swift Version: Xcode Default (Open Xcode Preferences; Components > Toolchains. If none, use Xcode Default.)
Please also mention which package manager you used and its version. Delete the
other package managers in this list:

Cocoapods: 1.6.1

### PR DESCRIPTION
**Pull request by VojtaStavik**
This PR fixes the regression introduced in a3ece4f. Closes #891 

The `defaultTestSuite` method wasn't called when the 'Selected tests' type of test suite was executed. This caused the `spec` method not being invoked and the examples for the given class were never built.

This PR changes the behaviour and introduces a new `buildExamplesIfNeeded` method. This method can be called safely multiple times. We call it from both the `defaultTestSuite` and `testInvocations` methods. This ensures the examples are built properly no matter which method is called (or in which order).

Checklist - While not every PR needs it, new features should consider this list:

 - [x] Does this have tests?
 - [x] Does this have documentation?
 - [ ] Does this break the public API (Requires major version bump)?
 - [ ] Is this a new feature (Requires minor version bump)?

### CODE REVIEW

**Comment by VojtaStavik** [comment]
Since the bug happens only when the tests are run from the IDE, we should restrict the tests in 
9722799 only for non-Darwin platforms?

**Comment by VojtaStavik** [comment]
@Quick/core can someone please take a look at this PR? Thank you!

**Comment by ikesyo** [comment]
It seems that by this fix, a crash occurs when using focused tests 😕 

```
2019-09-12 08:09:24.170519+0900 xctest[11754:14170830] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An exception occurred when building Quick's example groups.
Some possible reasons this might happen include:

- An 'expect(...).to' expectation was evaluated outside of an 'it', 'context', or 'describe' block
- 'sharedExamples' was called twice with the same name
- 'itBehavesLike' was called with a name that is not registered as a shared example

Here's the original exception: 'NSInternalInconsistencyException', reason: 'A shared example named 'combineLatest examples' has already been registered.', userInfo: '(null)''
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3d62d2fd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff67d0ba17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3d62d12f +[NSException raise:format:] + 201
	3   Quick                               0x0000000103642857 __34+[QuickSpec buildExamplesIfNeeded]_block_invo
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by VojtaStavik** [comment]
This crash looks familiar. Let me double check again. it’s been a while :)

**Pull request merged**
