### PR TITLE
Nimble++

### PR DESCRIPTION
**Pull request by phatblat**
to bring in Quick/Nimble#269

### CODE REVIEW

**Comment by phatblat** [comment]
Travis build stalled at the point where it crashed when run with xctool 0.2.8.

```
 [Info] Collecting info for testables...
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

Closed+reopened PR to trigger a new build.

**Comment by modocache** [comment]
Thanks! Yeah I was looking at the logs, very strange. What do you think happened?

**Comment by phatblat** [comment]
I'm not sure. I haven't been able to reproduce that xctool hang locally but I could repro the crash. I suspect the fix needs some more TLC.

**Comment by modocache** [comment]
Wait, so this time Circle CI failed? Oh, brother!

001bbfde24eeffebde6dee918543747a

I'll merge this. We can address CI flakiness due to xctool in another pull request. Thanks, @phatblat!! :bow:

**Comment by phatblat** [comment]
¯\_(ツ)_/¯

**Pull request merged**
