### PR TITLE
Add xctool tests to CI

### PR DESCRIPTION
**Pull request by mokagio**
See https://github.com/Quick/Quick/issues/389

For some reason my CircleCI setup has decided that I cannot run Xcode tests anymore, so I thought I might as well open the PR anyway and see if the tests will run for the Quick organization.

### CODE REVIEW

**Comment by mokagio** [comment]
Ok so the `xctool` tests for OS X are all passing but the command is failing anyway with some issue on the reporter. That's happening on my machine too but I wanted a double check. I'll look into that :hammer:

**Comment by mokagio** [comment]
This is ready for review, in my opinion.

What I've done:

- Added two Rake tasks to run the iOS and OS X tests using `xctool`.
- Updated `.travis.yml` and `circle.yml` to make sure `xctool` is up to date via `brew` before running the tests.
- Tweaked the `.yml`s to workaround a recent bug with a formula which makes `brew update` fail. See https://github.com/Homebrew/homebrew/issues/45616.
- Disabled, hopefully just temporarly, the `xctool` OS X tests run due an `xctool` bug, which fails the tests due to Quick's `pending` output using a `print`. See https://github.com/facebook/xctool/issues/314#issuecomment-152988101 and comments for more info, and see https://circleci.com/gh/mokagio/Quick/14 for a proof of the `xctool` OS X tests passing if `pending` doesn't print. Imho this is an `xctool` bug, so it is not up to Quick to change to accomodate it.

I'd like feedback on the Rake tasks naming style, see https://github.com/mokagio/Quick/commit/26ee8c19ab69899fa2c40ad152ae021fc3500e44#comments

**Comment by jeffh** [comment]
I'll take a look at it this weekend. Thanks for putting in the work @mokagio

**Comment by jeffh** [comment]
I've merged your changes while namespacing the rake task to be `test:xctool:osx` and `test:xctool:ios`.

Thanks @mokagio for the PR.

**Comment by mokagio** [comment]
I like the namespace choice you @jeffh made :)

Thanks for all the hard work you guys put in this awesome tool 💖

**Pull request merged**
