### PR TITLE
Added a `TestState` property wrapper.

### PR DESCRIPTION
**Pull request by CraigSiemens**
Adds a `TestShared` property wrapper as suggested in
- #1178

It will always reset a property to nil at the end of a test. If the property wrapper is created with a value, the value will be set at the start of a test.

Checklist - While not every PR needs it, new features should consider this list:

 - [x] Does this have tests?
 - [x] Does this have documentation?
 - [ ] Does this break the public API (Requires major version bump)?
 - [x] Is this a new feature (Requires minor version bump)?

### CODE REVIEW

**Review by younata — APPROVED** [review]
This is awesome! Thank you for taking care of it!

**Comment by CraigSiemens** [comment]
Any idea why the tests are failing? Each `expect` call in the tests I added is getting the error
```
error: expression is 'async' but is not marked with 'await'
```

I'm not seeing anything obviously different between my tests and the existing ones.

**Comment by younata** [comment]
> Any idea why the tests are failing? Each `expect` call in the tests I added is getting the error
> 
> ```
> error: expression is 'async' but is not marked with 'await'
> ```
> 
> I'm not seeing anything obviously different between my tests and the existing ones.

Oh. This is because Quick is using the 11.0 version of Nimble. This was fixed in the 11.2 version of Nimble. I just merged a [PR that brings it in](https://github.com/Quick/Quick/pull/1187). I updated your branch with now-current main. Hopefully there's nothing else.

**Comment by younata** [comment]
Ok, great. Tests have all passed. I'm sorry for this confusion. I'll merge it now.

Thank you so much for your contribution, @CraigSiemens!

**Pull request merged**
