### PR TITLE
Support single-test-case selective tests in Quick, fix for non-Quick

### PR DESCRIPTION
**Pull request by zacwest**
This adds filtering support for single-test-case executions of Quick tests. Although this is not super convenient in the Xcode UI, clicking the (X) after a failure will now execute only the failing test. This can also be done via command-line tests, which increases the usefulness for a CI system that e.g. can retry specific tests.

When a non-Quick class is asked to selectively test e.g. `SomeClass/some_specific_function` the default behavior of using `QuickTestSuite` to generate the suites will cause it to execute every test function, rather than just the selected ones. This change fixes this behavior by using the non-Swizzled variant of test suite selection when working against non-Quick selected tests.

### CODE REVIEW

**Comment by gemmakbarlow** [comment]
Any chance this can be merged in folks ? We are seeing this issue with Quick imported, and would *love* to get it resolved.

**Comment by zacwest** [comment]
I believe the Danger failure there is a false positive, otherwise this is still a functional change which resolves bugs in non-Quick tests (when Quick is in memory and swizzling) and fixes the handling within Quick.

**Comment by mokagio** [comment]
@zacwest correct. The [failure](https://github.com/Quick/Quick/pull/936/checks?check_run_id=1931067559#step:4:7) has to do with the token used by Danger not being having enough access rights.

```
Octokit::Forbidden: DELETE api.github.com/repos/Quick/Quick/issues/comments/554165261: 403 - Resource not accessible by integration // See: docs.github.com/rest/reference/issues#delete-an-issue-comment
```

**Comment by zacwest** [comment]
The Danger line still fails because of the access issue. Otherwise, I'm unsure what's going on in the Xcode 13 CI, but the same tests pass locally:

```
Test Case '-[Quick___iOSTests.QuickSpec_SelectedTests testNonQuickSpecRequestingNoTestCase]' started.
Test Case '-[Quick___iOSTests.QuickSpec_SelectedTests testNonQuickSpecRequestingNoTestCase]' passed (0.001 seconds).
Test Case '-[Quick___iOSTests.QuickSpec_SelectedTests testNonQuickSpecRequestingOneTestCase]' started.
Test Case '-[Quick___iOSTests.QuickSpec_SelectedTests testNonQuickSpecRequestingOneTestCase]' passed (0.001 seconds).
Test Case '-[Quick___iOSTests.QuickSpec_SelectedTests testQuickSpecRequestingNoTestCase]' started.
Test Case '-[Quick___iOSTests.QuickSpec_SelectedTests testQuickSpecRequestingNoTestCase]' passed (0.002 seconds).
Test Case '-[Quick___iOSTests.QuickSpec_SelectedTests testQuickSpecRequestingOneTestCase]' started.
Test Case '-[Quick___iOSTests.QuickSpec_SelectedTests testQuickSpecRequestingOneTestCase]' passed (0.001 seconds).
Test Case '-[Quick___iOSTests.QuickSpec_SelectedTests testQuickSpecTestInvocationsForAllTests]' started.
Test Case '-[Quick___iOSTests.QuickSpec_SelectedTests testQuickSpecTestInvocationsForAllTests]' passed (0.001 seconds).
Test Case '-[Quick___iOSTests.QuickSpec_SelectedTests testQuickSpecTestInvocationsForSelectedTests]' started.
Test Case '-[Quick___iOSTests.QuickSpec_SelectedTests testQuickSpecTestInvocationsForSelectedTests]' passed (0.001 seconds).
```

I did have to mutate what XCTest the Nimble framework was pointing to in my local checkout (it's trying to link against either the old location), perhaps there's some underlying oddness going on there.

**Comment by jessesquires** [comment]
Hey there! 👋🏼 

I'm a new maintainer for this project and I'm trying to get the next release out ASAP and also clean up old issues and old PRs. I'm closing all PRs older than 1-2 years, but that doesn't mean these changes are necessarily being rejected. If you are still interested in contributing these changes, please submit a new PR branching from the top of `main`.

We appreciate your work here and acknowledge the time and effort you put in to contribute! You're awesome. 💯 However, we are all volunteers here with limited capacity working for free. Unfortunately, that means we must close out stale issues and PRs to move the project forward in a reasonable way.

We apologize for the inconvenience and appreciate your understanding! 😎 ✌🏼

**Comment by zacwest** [comment]
🙄 I've been rebasing this for years. At the very least fix the underlying bug if you get a chance.

**Pull request closed without merging**
