### PR TITLE
[Translation] Review arrange act assert

### PR DESCRIPTION
**Pull request by LinShiwei**

### CODE REVIEW

**Comment by wongzigii** [comment]
LGTM

**Comment by modocache** [comment]
Thanks @LinShiwei and @wongzigii! I sent you both invites to join the Quick team. Please feel free to review and merge each others' work. Contributions to other parts of Quick and Nimble are also welcome, of course! :)

**Comment by wongzigii** [comment]
Thank you @modocache !!

**Comment by LinShiwei** [comment]
It's my honor to join Quick. Thanks! @modocache

**Pull request merged**
