### PR TITLE
Release process update

### PR DESCRIPTION
**Pull request by ashfurrow**
Similar work to https://github.com/Quick/Nimble/pull/284 . ~~Waiting to hear back about attaching binary releases before removing that from the script, too.~~

### CODE REVIEW

**Comment by phatblat** [comment]
Very nice. Is this ready to merge? CI failures don't apply to this change.

**Comment by phatblat** [comment]
Just noticed #475 and #467. These changes should be incorporated into the if we continue with converting the release script.

**Comment by briancroom** [comment]
Let's do it! 👍

**Comment by briancroom** [comment]
Ah yes, I forgot about that work. It looks like we've let that get pretty stale, unfortunately. I think it's reasonable to merge this in now since it's ready, and include doc updates in #475 when that one is ready to go.

**Comment by phatblat** [comment]
Yep, agree completely.

**Pull request merged**
