### PR TITLE
[WIP] Swift 3.0 Compatibility

### PR DESCRIPTION
**Pull request by norio-nomura**
- Uses wrapper that converting from Swift 3.0 API to Swift 2.2 API.
- Includes #497
- Uses swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a
- Depends on https://github.com/Quick/Nimble/pull/277. `Package.swift` uses my fork until that merged.
- [x] Re-organize for `swift test`. Can we do that?

### CODE REVIEW

**Comment by norio-nomura** [comment]
>  Re-organize for swift test. Can we do that?

I'm trying to pass `swift test`, but it stopped by bug of swift package manager: https://bugs.swift.org/browse/SR-1159
On Quick's case, `swift test` runs test of Nimble instead of Quick.

**Comment by briancroom** [comment]
Hey @norio-nomura, do you think you could update this for the latest Swift development snapshot? I'm curious whether the SwiftPM bug you were running into is fixed with the version in that package.

**Comment by norio-nomura** [comment]
That bug has been fixed in `swift-DEVELOPMENT-SNAPSHOT-2016-04-12`.
But I can't update this PR for supporting `swift-DEVELOPMENT-SNAPSHOT-2016-04-12` because of the reason written on https://github.com/Quick/Nimble/pull/277#issuecomment-213229875.

**Comment by liscio** [comment]
I have issued a PR against Norio's fork of Quick that allow it to compile & pass all tests for macOS and iOS targets here: https://github.com/norio-nomura/Quick/pull/1

**Comment by NachoSoto** [comment]
Beta 2 compatibility: https://github.com/norio-nomura/Quick/pull/2

**Comment by andersio** [comment]
Hi, I have pushed a PR to lower the deployment target to 10.9. Please have a look.
https://github.com/norio-nomura/Quick/pull/4

**Comment by andersio** [comment]
Would you like to check if the "last migration" attributes are set? Xcode keeps prompting for running a migration on Quick.

**Comment by norio-nomura** [comment]
Now, testing Commandant on Linux using this PR is passing on Travis-CI. https://travis-ci.org/norio-nomura/Commandant/jobs/144637340

**Comment by norio-nomura** [comment]
I almost gave up to support Swift Package Manager on OS X.

**Comment by modocache** [comment]
@norio-nomura Is there anything I can help with here?

**Comment by norio-nomura** [comment]
@modocache Maybe I'll need to push some branch for explaining what I tried.

**Comment by pcantrell** [comment]
This PR isn’t building on Xcode 8 beta 6. Should I submit PRs to fix against this PR, or is there a more up-to-date place to send them?

**Comment by ikesyo** [comment]
beta 6 support: https://github.com/norio-nomura/Quick/pull/7

**Comment by norio-nomura** [comment]
Now it compatible with swift-3.0-PREVIEW-6 and my Commandant fork passed test with that: https://travis-ci.org/norio-nomura/Commandant/builds/154734861
Thanks @ikesyo!

**Comment by ikesyo** [comment]
I'd like to officially manage Swift 3 migration in this repo and I've created `swift-3.0` branch. @norio-nomura Could you change the base branch of this PR to that branch? Once that is done, I would merge this and submit a new PR from the branch to `master`. Then, subsequent PRs for Swift 3 should be targeted on the branch.

**Comment by norio-nomura** [comment]
@ikesyo Thanks! I have changed base branch to `swift-3.0`.

**Comment by ikesyo** [comment]
Thank you @norio-nomura and all who contributed to Swift 3 support on this PR! 🎉

**Pull request merged**
