### PR TITLE
[WIP] Updates to support Swift package manager.

### PR DESCRIPTION
**Pull request by paulyoung**
I've marked this as WIP because:

giphy

Here's what `swift build` says:

```
Compiling Swift Module 'Quick' (16 sources)
Linking Library:  .build/debug/Quick.a
/Applications/Xcode7.1.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/paulyoung/git/Quick/Quick/.build/debug/Quick.a(Closures.swift.o) has no symbols
```

### CODE REVIEW

**Comment by paulyoung** [comment]
I think the CI build failure is some rake task issue and unrelated to these changes.

**Comment by jeffh** [comment]
Sorry about that @paulyoung, I pushed a fix onto master. I forgot to update CircleCI. It should be green when you rebase.

**Comment by paulyoung** [comment]
@jeffh no worries! I just rebased an pushed.

**Comment by briancroom** [comment]
@paulyoung it looks like the `file has no symbols` warning is being tracked [here](https://bugs.swift.org/browse/SR-24) and is pretty harmless.

**Comment by modocache** [comment]
CI showed failures on Circle CI. The Travis CI build had been reported as a failure as well, but all the output had said it succeeded...?

Anyway, I pulled, fixed some conflicts from #442, and ran the tests myself. Everything seems to have passed, so :shipit:!

Thanks for all the contributions, @paulyoung! :100:

**Pull request merged**
