### PR TITLE
Improved documentation

### PR DESCRIPTION
**Pull request by modocache**
The README currently contains information on what Quick is, why you'd
want to use Quick, how to install Quick, and more. This makes it
extremely long, and difficult to read.

Split the README up into a bunch of separate Markdown files, compiled in
a directory called `Documentation`. The documentation directory mostly
contains instructions on using Quick. However, since some aspects of
Quick are best appreciated when one has some knowledge of how to write
unit tests in Swift/Objective-C, the documentation has instructions on
that as well.

/cc @orta @jonreid

### CODE REVIEW

**Comment by modocache** [comment]
I think this is a significant improvement, and I'm excited to have it in sooner rather than later, so I'm merging! :cocktail: :boat:

**Comment by orta** [comment]
Significant is an understatement. You're offering motivations for testing, not _just) using quick/nimble. :+1:

**Comment by jeffh** [comment]
It's worth adding some link on the README to this :)

**Comment by mkauppila** [comment]
Wow, this is a significant improvement. Huge :+1: and :cake: @modocache

**Pull request merged**
