### PR TITLE
Switch back to xctool release builds

### PR DESCRIPTION
**Pull request by phatblat**
0.2.9 is out now

### CODE REVIEW

**Comment by ashfurrow** [comment]
Is this PR for https://github.com/Quick/Quick/issues/520 ?

**Comment by phatblat** [comment]
No, just didn't want to forget to switch back. Technically, it won't make a difference right now since there haven't been any new commits to xctool master since the 0.2.9 release.

**Comment by ashfurrow** [comment]
OK, cool! This looks good to merge from my end.

**Comment by briancroom** [comment]
Thanks @phatblat!

**Pull request merged**
